/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TokenRouteImport } from './routes/token'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as CrudeRouteImport } from './routes/crude'
import { Route as IndexRouteImport } from './routes/index'

const TokenRoute = TokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const CrudeRoute = CrudeRouteImport.update({
  id: '/crude',
  path: '/crude',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crude': typeof CrudeRoute
  '/signin': typeof SigninRoute
  '/token': typeof TokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crude': typeof CrudeRoute
  '/signin': typeof SigninRoute
  '/token': typeof TokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crude': typeof CrudeRoute
  '/signin': typeof SigninRoute
  '/token': typeof TokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crude' | '/signin' | '/token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crude' | '/signin' | '/token'
  id: '__root__' | '/' | '/crude' | '/signin' | '/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrudeRoute: typeof CrudeRoute
  SigninRoute: typeof SigninRoute
  TokenRoute: typeof TokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/token': {
      id: '/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crude': {
      id: '/crude'
      path: '/crude'
      fullPath: '/crude'
      preLoaderRoute: typeof CrudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrudeRoute: CrudeRoute,
  SigninRoute: SigninRoute,
  TokenRoute: TokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
